### ISSUE TITLE
Possible to get device name/id?

### ISSUE THREAD

**Issue by expertsonline** [mikejac/node-red-contrib-google-smarthome#308] opened 2022-08-08 04:06 UTC
Hi - I wanted to check if there is any way to get the device name that invoked a state change? I have multiple google home mini speakers at home and so I would like to find out which room the command came from so that I can have devices with the same name across the house.

e.g. I have 3 rooms, living room, bedroom and dining room. All three of them have a smart fan.
If in the dining room, I say turn on the fan, I would like some information to confirm the command is coming from the dining room device, so I know which fan to turn on.

Hope this makes sense....any thoughts on how this could be achieved would be greatly appreciated.

Thanks

**Comment by ChutneyMary** [comment] 2022-08-08 04:23
I'm a bit confused because the functionality you want is already available in the Google device node.

For example, I have multiple windows throughout the house with a separate Google node for each window group. The Room hint in the Google Node defines the location.

If the Kitchen Google Home Mini hears the command "Open the windows", only the kitchen window opens.
If any of the Google Home Mini's in the house hears "Open the kitchen windows", only the kitchen window opens.
If the command "Open all the windows" is spoken, all the windows in the house open.

Have I mis-understood the problem your trying to solve?

**Comment by expertsonline** [comment] 2022-08-08 05:02
Thanks for explaining - I was not aware that is how room hint worked. Let me do some testing and report back!

**Comment by Caprico85** [comment] 2022-08-08 06:33
I can confirm. Unless you say a specific room ("Open the kitchen windows") or a specific device ("Turn on the desk lamp"), all commands are referenced to the devices assigned to the same room as the speaker only. Room assignment can happen via room hint or manually in the app.

From the API perspective there is nothing we can do. Google only sends the command, not the device it originated from.

**Closed** 2023-10-17 19:41 UTC
